public abstract class Pizza {
    protected String name; // *field (variable within the class) Line is generated by AI

    public String getName() {
        return name;
    }
    public void setName(String name){
        this.name = name;
    }

    public abstract void prepare();
    public abstract void bake();
    public abstract void cut();
    public abstract void box();
}

//Pizza --> Cheese --> Greek-->PePPeroni
//Same methods different behaviors